pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: '<branch_name>', credentialsId: '', url: '<repository_url>'
            }
        }

        stage('Build Project') {
            steps {
                sh 'cd <path_to_your_project>'
                sh './build.sh'  // Assuming you have a build script named build.sh
            }
        }

        stage('Run Tests') {
            steps {
                sh 'cd <path_to_your_project>'
                sh './test.sh'   // Assuming you have a test script named test.sh
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/*.log'  // Archive logs from all stages
        }
        success {
            echo 'Build succeeded! You can add email/slack notification here.'
        }
        failure {
            echo 'Build failed! You can add email/slack notification here.'
        }
    }
}
